### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 4000000
trust_remote_code: true
deepspeed: examples/deepspeed/ds_z2_config.json

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false

### dataset
dataset: easyr1-114k-hard-qwen7b-easy-gta1-4MP-nores-jedi-fix-synced-aug-jitter
template: qwen2_vl
cutoff_len: 32000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl_7b_easyr1_114k_hard_qwen7b_easy_gta1_4MP_no_resolution_in_prompt_lr_1_0e-06_bs_1_epochs_1.0_max_pixels_4000000_deepspeed
logging_steps: 10
save_steps: 250
plot_loss: true
include_effective_tokens_per_second: true
overwrite_output_dir: false
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500